spring:
  sql:
    init:
      mode: ALWAYS
      data-locations:
        - classpath:/data.sql

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: pa


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    root: info